swagger: '2.0'
x-asee-visibility: public
info:
  version: v1
  title: Profile API
  description: 'Profile API gives you access to facts on customers, their behavior and usage of arrangements so you can optimize real-time operational decisions and interactions.'
  contact:
    name: Milan Drakulic
    url: https://bankapi.net/docs/public/profile-getstarted.html
    email: milan.drakulic@asseco-see.rs
host: bankapi.net
basePath: /v1/profile
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Individual profiles
    description: Working with indvididual profiles
  - name: Organization profiles
    description: Working with organization profiles
  - name: Arrangement profiles
    description: Working with arrangement profiles
  - name: Classifications
    description: Working with classifications

paths:
  '/individual-profiles/{party-number}':
    get:
      summary: Get profile of specific individual
      tags:
        - Individual profiles
      x-asee-tags:
        - Shapeable
      operationId: IndividualProfiles_Get
      parameters:
        - $ref: '#/parameters/party-number-param'
        - $ref: '#/parameters/include-param'
        - $ref: '#/parameters/trim-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/individual-profile'
        default:
          $ref: '#/responses/default-error-response'

  '/organization-profiles/{party-number}':
    get:
      summary: Get profile of specific organization
      tags:
        - Organization profiles
      x-asee-tags:
        - Shapeable
      operationId: OrganizationProfiles_Get
      parameters:
        - $ref: '#/parameters/party-number-param'
        - $ref: '#/parameters/include-param'
        - $ref: '#/parameters/trim-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/organization-profile'
        default:
          $ref: '#/responses/default-error-response'

  '/arrangement-profiles/{arrangement-number}':
    get:
      summary: Get profile of specific arrangemnt
      tags:
        - Arrangement profiles
      x-asee-tags:
        - Shapeable
      operationId: ArrangementProfiles_Get
      parameters:
        - $ref: '#/parameters/arrangement-number-param'
        - $ref: '#/parameters/include-param'
        - $ref: '#/parameters/trim-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/arrangement-profile'
        default:
          $ref: '#/responses/default-error-response'


  /classifications:
    get:
      summary: List all classification schemas used by the API
      description: Some fields and parameters have been restricted to a list of allowed lookup values maintained by the bank. This method lists all schemas used in this API.
      operationId: "Classifications_GetList"
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/classification-list'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Classifications

  /classifications/{schema-id}:
    get:
      summary: List values allowed by given classification schema.
      description: Returns all classification values for chosen classification.
      operationId: Classifications_Get
      parameters:
        - $ref: '#/parameters/schema-id-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/classification'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Classifications

responses:
  default-error-response:
    description: "Besides specific status codes above, other standard http [status codes](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) can be returned for each request. To learn more see general guidance on [error handling](common-getstarted.html#error-handling)"

parameters:
  party-number-param:
    description: "Unique identifier of party in bank's records. Also known as customer number"
    in: path
    name: party-number
    required: true
    type: string
  arrangement-number-param:
    description: "Unique identifier of an arrangement. For account arrangements, this should be the same as primary account number."
    in: path
    name: arrangement-number
    required: true
    type: string

  schema-id-param:
    name: schema-id
    description: Identifier of classification schema
    in: path
    required: true
    type: string
  include-param:
    description: List of fields to include in response. For more information see general guidance on [response shaping](common-getstarted.html#shaping)
    in: query
    name: include
    type: array
    items:
      type: string
    collectionFormat: csv
    x-asee-common: true
  trim-param:
    description: List of fields to trim from response. For more information see general guidance on [response shaping](common-getstarted.html#shaping)
    in: query
    name: trim
    type: array
    items:
      type: string
    collectionFormat: csv
    x-asee-common: true

definitions:
  individual-profile:
    properties:
      party-number:
        description: Unique identifier of the party. Also known as customer number.
        type: string
      is-employee:
        description: Indicator whether individual is employee of the bank
        type: boolean
      lifecycle-status:
        description:  |
          Distinguishes between individuals according to whether or not they are living or if their status is unknown
          For a list of possible values see [individual-profile-lifecycle-statuses](profile-classifications.html#individual-profile-lifecycle-statuses) enumeration.
        type: string
        enum: [living, deceased, missing, unknown]
      channel:
        $ref: '#/definitions/channel-behavior'
      product:
        $ref: '#/definitions/product-usage'
      demographic:
        $ref: '#/definitions/demographic-profile'
      customer:
        $ref: '#/definitions/customer-profile'
      financial:
        $ref: '#/definitions/individual-financial-profile'
      household:
        $ref: '#/definitions/household-profile'
      social:
        $ref: '#/definitions/social-media-behavior'
    example:
      party-number: nodjo001
      is-employee: false
      lifecycle-status: living
      product:
        products-used: 3
        accounts-used: 2
        average-liabilities: 0
        average-deposits: 6000000
        credit-limit-utilization: 0
        total-arrears: 0
        receives-salary: false
        uses-current-account: true
        uses-credit-card: false
        uses-overdraft: false
        uses-mortgage: false
        uses-consumer-credit: false
      customer:
        kind: individual
        status: active
        segment: hnwi
        relationship-age-with-bank: 18
        lifetime-value: 254800000
        credit-score: 680
        retention-score: 74
      demographic:
        gender: male
        age: 28
        country-of-residence: RS
        marital-status: married
        highest-education: high-school
        current-occupation: professional-athlete
        employment-status: employed
        years-with-employer: 8
        work-experience: 8
        preferred-language: sr-Latn-RS
      financial:
        disposable-income: 120000000
        regular-income: 100000000
        additional-income: 20000000
        net-worth: 2400000000
        car-ownership: owns
      household:
        housing-tenure: owned-without-mortgage
        monthly-income: 120000000
        size: 3
        years-at-address: 4
        dependent-children: 1
        dependent-adults: 1
      channel:
        mobile-sessions: 62
        web-sessions: 23
        atm-visits: 31
        branch-visits: 1
        cc-calls: 1
        mobile-transactions: 46
        web-transactions: 16
        atm-transactions: 38
        branch-transactions: 4
        cc-transactions: 0
        unresolved-issues: 0
      social:
        facebook-friends: 82
        facebook-posts: 283
        facebook-comments: 465
        linked-in-connections: 0
        linked-in-posts: 0
        linked-in-comments: 0
        twitter-followers: 5151021
        twitter-tweets: 2251
        twitter-mentions: 98449821

  organization-profile:
    properties:
      party-number:
        description: Unique identifier of the party. Also known as customer number.
        type: string
      legal-structure:
        type: string
        x-asee-classification: legal-structure
        description: |
          'Classifies organizations based on their legal form or structure. For example, `public-organization`, `partnership`, `sole-proprietorship`, `limited-company`.such as trust, company, charity, or estate.
          For a complete list of possible values see [legal-structure](party-classifications.html#legal-structure)'
      organization-purpose:
        type: string
        x-asee-classification: organization-purpose
        description: |
          'Distinguishes between organizations according to their purpose or format; for example, `association` and `public-service`.
          For a complete list of possible values see [organization-purpose](party-classifications.html#organization-purpose)'
      is-sole-trader:
        type: boolean
        description: 'A flag indicating that this organization represents the business aspects of an individual operating as a sole trader. The relevant Individual can be traced through the party relationship.'
      years-of-operation:
        description: Years of operation since organization was formally established
        type: integer
        format: int32
      number-of-employees:
        description: Number of employees at organization
        type: integer
        format: int32
      lifecycle-status:
        description: |
          Distinguishes between organizations according to the life cycle states through which they may pass over time
          For a list of possible values see [organization-profile-lifecycle-statuses](profile-classifications.html#organization-profile-lifecycle-statuses) enumeration.
        type: string
        enum: [active, closed, formed, potential, inactive, suspended, unknown]
      channel:
        $ref: '#/definitions/channel-behavior'
      product:
        $ref: '#/definitions/product-usage'
      customer:
        $ref: '#/definitions/customer-profile'
    example:
      party-number: resno003
      legal-structure: limited-liability-company
      organization-purpose: profit
      is-sole-trader: false
      years-of-operation: 6
      number-of-employees: 48
      lifecycle-status: active
      product:
        products-used: 3
        accounts-used: 2
        average-liabilities: 0
        average-deposits: 6000000
        credit-limit-utilization: 0
        total-arrears: 0
        receives-salary: false
        uses-current-account: true
        uses-credit-card: false
        uses-overdraft: false
        uses-mortgage: false
        uses-consumer-credit: false
      customer:
        kind: small-business
        status: active
        segment: sme
        relationship-age-with-bank: 18
        lifetime-value: 254800
        credit-score: 680
        retention-score: 74
      channel:
        mobile-sessions: 62
        web-sessions: 23
        atm-visits: 31
        branch-visits: 1
        cc-calls: 1
        mobile-transactions: 46
        web-transactions: 16
        atm-transactions: 38
        branch-transactions: 4
        cc-transactions: 0
        unresolved-issues: 0

  arrangement-profile:
    properties:
      arrangement-number:
        type: string
        description: "Unique identifier of an account arrangementsuch as primary account number"
      kind:
        type: string
        description: |
          Primary classification of arrangements according to product type.
          For a list of possible values see [arrangement-kinds](arrangement-classifications.html#arrangement-kinds) enumeration.
        enum:
        - current-account
        - demand-deposit
        - term-deposit
        - term-loan
        - overdraft-facility
        - credit-facility
        - credit-card-facility
      lifecycle-status:
        description: |
          Distinguishes between arrangements according to life cycle states through which they may pass over time
          For a list of possible values see [arrangement-profile-lifecycle-statuses](profile-classifications.html#arrangement-profile-lifecycle-statuses) enumeration.
        type: string
        enum: [effective, termminated, completed, suspended, dormant]
      next-installment-amount:
        type: number
        format: double
        description: Amount of next monthly installment
      minimum-repayment-amount:
        type: number
        format: double
        description: Minimum repayment given next monthly installment and any overdue payments
      total-repaid-amount:
        type: number
        format: double
        description: Total sum of all full or partial repayments      
      next-installment-date:
        type: string
        format: date
        description: Date when next installment is due
      remaining-installments:
        type: integer
        format: int32
        description: Number of remaining installments
      days-overdue:
        type: integer
        format: int32
        description: Number of days minimum payment is outstanding past its due date
      amount-overdue:
        type: integer
        format: int32
        description: Total amount outstanding past its due date
      first-salary-date:
        type: string
        format: date
        description: Date when first salary income was booked on current account arrangement
      first-transaction-date:
        type: string
        format: date
        description: Date when first financial transaction was booked against account arrangement
      last-transaction-date:
        type: string
        format: date
        description: Date when last financial transaction was booked against account arrangement
      last-statement-date:
        type: string
        format: date
        description: Date when last statement was generated for account arrangement
      first-disbursement-date:
        type: string
        format: date
        description: Date when first disbursement was made to the customer from the arrangement
      uncleared-checks:
        description: Number of issued checks that are still in circullation and have not yet cleared
        type: integer
        minimum: 0
        format: int32

    example:
      arrangement-number: "002010001010112"
      kind: current-account
      lifecycle-status: effective
      first-salary-date: 2015-08-30
      first-transaction-date: 2015-09-01
      last-transaction-date: 2016-01-21
      last-statement-date: 2015-12-31
  product-usage:
    properties:
      products-used:
        description: "Number of products which are currently used by the customer"
        type: integer
        format: int32
      accounts-used:
        description: "Number of account arrangements which are currently used by the customer"
        type: integer
        format: int32
      average-liabilities:
        type: number
        format: double
        description: Average balance of total customer liabilities to bank
      average-deposits:
        type: number
        format: double
        description: Average balance of total customer deposits held at bank
      credit-limit-utilization:
        type: number
        format: double
        description: Credit limit utilization ratio is the measure of utilization of the credit limit extended to customer expressed percentage
      total-arrears:
        type: number
        format: double
        description: Total amount of arrears for the customer such as late payments on loans or credit facilities
      receives-salary:
        description: Indicator whether customer receives salary to account held at bank
        type: boolean
      uses-current-account:
        description: Indicator whether customer uses current account with bank
        type: boolean
      uses-credit-card:
        description: Indicator whether customer uses credit card  with bank
        type: boolean
      uses-overdraft:
        description: Indicator whether customer uses overdraft facility with bank
        type: boolean
      uses-mortgage:
        description: Indicator whether customer uses mortgage loan with bank
        type: boolean
      uses-consumer-credit:
        description: Indicator whether customer uses consumer loan with bank
        type: boolean

  customer-profile:
    properties:
      kind:
        type: string
        x-asee-classification: customer-taxonomy
        description: 'Classifies customers according to taxonomy defined by bank. For a complete list of possible values see [customer-taxonomies](party-classifications.html#customer-taxonomies) classification'
      status:
        description: |
          'Enumer identifies the state of a customer within a lifecycle model.
          For a list of values see in [customer-statuses](party-classifications.html#customer-statuses) enumeration'
        x-asee-enumeration: customer-statuses
        type: string
        enum: [potential, prospective, active, dormant, former, declined, rejected]
      segment:
        type: string
        x-asee-classification: customer-segment
        description: 'Classifies the customers into segments according to bank requirements. For a complete list of possible values see [customer-segments](party-classifications.html#customer-segments) classification'
      relationship-age-with-bank:
        description: Number of months for which a customer has had a relationship with the bank - activated first product
        format: int32
        type: integer
      lifetime-value:
        description: Total projected earnings of a customer to the bank over the probable lifetime of that customer
        type: number
        format: double
      credit-score:
        type: integer
        format: int32
        description: "Credit score for the customer, which is derived as a numeric score from several different measures used to assess a Customer's risk of default"
      retention-score:
        type: integer
        format: int32
        description: "The scoring of the likelihood of the customer staying with the bank"

  demographic-profile:
    properties:
      gender:
        description: 'Gender is the characteristic pertaining to, and differentiating between, masculinity and femininity'
        type: string
        enum: [female, male, unknown]
      age:
        description: Individual's age
        format: int32
        type: integer
      country-of-residence:
        description: Individual's country of residence
        type: string
        format: ISO 3166-1 alpha-2
        minLength: 2
        maxLength: 2
      marital-status:
        description: |
          Marital status
          For a list of possible values see [marital-statuses](party-classifications.html#marital-statuses) enumeration.
        enum:
          - divorced
          - common-law-marriage
          - married
          - single
          - widowed
          - unknown
        type: string
      highest-education:
        description: |
          Highest educational level.
          For complete list of possible values see [education-levels](profile-classifications.html#education-levels) classification.
        type: string
        x-asee-classification: education-levels
      current-occupation:
        description: |
          Distinguishes between individuals according to a person's work or business engagement. For example, farmer, free-professional, tradesperson, author, business-owner, consultant, doctor, dentist, economist, homemaker etc.
          For complete list of possible values see [occupations](profile-classifications.html#occupations) classification.
        type: string
        x-asee-classification: occupations
      employment-status:
        description: |
          Employment status of the individual.
          For complete list of possible values see [employment-statuses](party-classifications.html#employment-statuses) enumeration.
        type: string
        enum:
          - employed
          - not-employed
          - retired
          - shop-owner
          - farmer
          - leave-of-absence
          - part-time-job
          - unknown
      years-with-employer:
        description: How many years is individual working for current employer
        format: int32
        type: integer
      work-experience:
        description: Total working experience in years
        format: int32
        type: integer
      preferred-language:
        description: Language preferred by individual as standard BCP47 language tag. Example `sr-Latn-RS` or `en-US`
        type: string
        format: BCP47

  individual-financial-profile:
    properties:
      disposable-income:
        type: number
        format: double
        description: Total monthly disposable income of individual including regular and additional sources after all deductions are subtracted
      regular-income:
        type: number
        format: double
        description: Total monthly income of individual from regular sources such as employment, pension etc.
      additional-income:
        type: number
        format: double
        description: Total monthly additional income of individual from additional sources such as rent, contract, alimony etc.
      net-worth:
        type: number
        format: double
        description: Total assets minus total liabilities of individual. This is based on information available to the bank and is used for assessing the wealth of customers or prospective customers
      car-ownership:
        description: |
          Car assets.
          For complete list of possible values see [car-ownerships](offer-classifications.html#car-ownerships) enumeration.
        type: string
        enum: [owns, does-not-own, unknown]

  household-profile:
    properties:
      housing-tenure:
        type: string
        description: |
          For a list of possible values see [housing-tenures](profile-classifications.html#housing-tenures) enumeration.
        enum: [owned-with-mortgage, owned-without-mortgage, rented, unknown]
      monthly-income:
        type: number
        format: double
        description: Total monthly income of household that individual belongs to
      size:
        description: Number of household members.
        format: int32
        type: integer
      years-at-address:
        description: How many years is household at current address
        format: int32
        type: integer
      dependent-children:
        description: Number of dependent children
        format: int32
        type: integer
      dependent-adults:
        description: Number of dependent adults
        format: int32
        type: integer

  channel-behavior:
    properties:
      mobile-sessions:
        description: Number of mobile channel sessions in recent period (usually 6 mohths)
        format: int32
        type: integer
      web-sessions:
        description: Number of web channel sessions in recent period (usually 6 mohths)
        format: int32
        type: integer
      atm-visits:
        description: Number of atm visits in recent period (usually 6 mohths)
        format: int32
        type: integer
      branch-visits:
        description: Number of branch visits in recent period (usually 6 mohths)
        format: int32
        type: integer
      cc-calls:
        description: Number of contact center calls in recent period (usually 6 mohths)
        format: int32
        type: integer
      mobile-transactions:
        description: Number of transactions initiated via mobile channel in recent period (usually 6 mohths)
        format: int32
        type: integer
      web-transactions:
        description: Number of transactions initiated via web channel in recent period (usually 6 mohths)
        format: int32
        type: integer
      atm-transactions:
        description: Number of transactions initiated via atm in recent period (usually 6 mohths)
        format: int32
        type: integer
      branch-transactions:
        description: Number of transactions initiated via branch in recent period (usually 6 mohths)
        format: int32
        type: integer
      cc-transactions:
        description: Number of transactions initiated via contact center in recent period (usually 6 mohths)
        format: int32
        type: integer
      unresolved-issues:
        description: Number of unresolved issues such as complaints customer has with bank
        format: int32
        type: integer

  social-media-behavior:
    properties:
      facebook-friends:
        description: "Number of facebook friends associated with customer"
        type: integer
        format: int32
      facebook-posts:
        description: "Number of facebook posts associated with customer"
        type: integer
        format: int32
      facebook-comments:
        description: "Number of facebook comments associated with customer"
        type: integer
        format: int32
      linked-in-connections:
        description: "Number of linked-in connections associated with customer"
        type: integer
        format: int32
      linked-in-posts:
        description: "Number of linked-in posts associated with customer"
        type: integer
        format: int32
      linked-in-comments:
        description: "Number of linked-in comments associated with customer"
        type: integer
        format: int32
      twitter-followers:
        description: "Number of twitter followers associated with customer"
        type: integer
        format: int32
      twitter-tweets:
        description: "Number of twitter followers associated with customer"
        type: integer
        format: int32
      twitter-mentions:
        description: "Number of twitter followers associated with customer"
        type: integer
        format: int32

  classification-value:
    type: object
    description: Classification value
    properties:
      literal:
        description: Literal that uniquely identifies classification value
        type: string
      code:
        description: Optional numerical code of classification value
        type: string
      description:
        description: Description of classification value
        type: string
      parent-literal:
        description: Optional literal of parent classification value if schema is hierarchical
        type: string
    example:
      literal: billing
      code: "2"
      description: Contact may be used to provide party with details of their liabilities to the bank

  classification-list:
    description: List of classification schemas
    type: object
    properties:
      items:
        description: List of classification schemas
        items:
          $ref: "#/definitions/classification-info"
        type: array
    example:
      -
        schema-id: filing-purpose
        name: Filing Purpose
        description: List of possible uses of document in business context. Commonly used filing purposes are document, customer-picture
      -
        schema-id: folder-purpose
        name: Folder Purpose
        description: List of possible uses of a folder in business context.

  classification-info:
    description: Basic information on classification schema
    properties:
      schema-id:
        type: string
        description: Unique literal that identifies the classification schema. Always in `lowercase-dash` convention.
      name:
        type: string
        description: User friendly name of classification
      description:
        type: string
        description: Description of a classification
    example:
      schema-id: filing-purpose
      name: Filing Purpose
      description: List of possible uses of document in business context. Commonly used filing purposes are document, customer-picture

  classification:
    type: object
    description: Classification schema details
    properties:
      schema-id:
        type: string
        description: Unique literal that identifies the classification schema. Always in `lowercase-dash` convention.
      name:
        type: string
        description: User friendly name of classification
      description:
        type: string
        description: Description of a classification
      values:
        description: List of allowed classification values
        type: array
        items:
          $ref: "#/definitions/classification-value"
    example:
      schema-id: contact-purpose
      name: Contact Purpose
      description: List of possible uses of contact in business context. Commonly used filing purposes are billing, marketing
      values:
        - literal: billing
          code: "1"
          description: Contact may be used to provide party with details of their liabilities to the bank
        - literal: marketing
          code: "2"
          description: Contact may be used to provide party with details of offers
        - literal: reporting
          code: "3"
          description: Contact may be used to provide party with reports on their account
