swagger: '2.0'
x-asee-visibility: internal
info:
  version: v1
  title: Content Management Events
  description: 'Events described here tell you what happens to **documents** and **folders** in content respository. To learn more about general approach to event processing see [How to work with events]().'
  contact:
    name: Aleksandar Milosevic
    url: https://bankapi.net/docs/public/content-getstarted.html
    email: aca@see.asseco.com

host: bankapi.net
basePath: /v1/content
schemes:
  - http
  - https
produces:
  - application/json
paths:
  /events:
    get:
      summary: Dummy operation to help generate event definitions
      operationId: GetEvents
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/event'
definitions:
  event:
    description: Event base model is redefined within each API to provide list of kinds
    type: object
    discriminator: kind
    required:
      - kind
    properties:
      kind:
        type: string
        description: Unique kind of event
        enum:
          - document-filed
          - document-moved
          - document-deleted
          - folder-created
          - dolder-moved
          - folder-deleted
      occurred-on:
        type: string
        format: date-time
        description: Time when an event occurred
      id:
        type: string
        format: uuid
        description: Unique identifier of event instance in UUID format
      aggregate-id:
        type: string
        description: Unique identifier of `document` or `folder` that published the event
      aggregate-kind:
        type: string
        description: Kind of resource (aggregate) that this event describes. In content management this can be `document` or `folder`
        enum:
          - document
          - folder
    example:
      kind: document-filed
      occurred-on: '2015-11-19T13:21:01.000Z'
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
      aggregate-id: 3e0f7ce312e5
      aggregate-kind: document
      file-name: photo.jpg
  document-filed:
    type: object
    description: A new document has been filed to repository
    allOf:
      - $ref: '#/definitions/event'
      - type: object
        properties:
          file-name:
            type: string
    example:
      kind: document-filed
      occurred-on: '2015-11-19T13:21:01.000Z'
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
      aggregate-id: 3e0f7ce312e5
      aggregate-kind: document
      file-name: photo.jpg
  document-moved:
    type: object
    description: A document has been moved to different folder
    allOf:
      - $ref: '#/definitions/event'
      - type: object
        properties:
          file-name:
            type: string
          old-path:
            type: string
          new-path:
            type: string
    example:
      kind: document-moved
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
      aggregate-id: 3e0f7ce312e5
      aggregate-kind: document
      file-name: photo.jpg
      old-path: web/jabon0007/images/
      new-path: web/jabon0007/archive/images/
  document-updated:
    type: object
    description: Folder properties were updated
    allOf:
      - $ref: '#/definitions/event'
      - type: object
        properties:
          path:
            type: string
          file-name:
            type: string
          changes:
            type: array
            items:
              $ref: '#/definitions/change'
    example:
      kind: document-properties-updated
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
      aggregate-id: 3e0f7ce312e5
      aggregate-kind: document
      path: web/jabon0007/applications/wi738811/scans
      file-name: photo.jpg
      updates:
        - name: ou
          old: 2301
          new: 1000
        - name: thumbnail
          old: 'no'
          new: 'yes'
  document-deleted:
    type: object
    description: A folder was deleted
    allOf:
      - $ref: '#/definitions/event'
      - type: object
        properties:
          path:
            type: string
    example:
      kind: folder-deleted
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
      aggregate-id: 3e0f7ce312e5
      aggregate-kind: folder
      path: web/jabon0007/
      file-name: photo.jpg
  folder-created:
    type: object
    description: A new folder was created
    allOf:
      - $ref: '#/definitions/event'
      - type: object
        properties:
          path:
            type: string
    example:
      kind: folder-created
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
      aggregate-id: 3e0f7ce312e5
      aggregate-kind: folder
      path: web/jabon0007/
  folder-moved:
    type: object
    description: A folder was moved to different parent folder
    allOf:
      - $ref: '#/definitions/event'
      - type: object
        properties:
          path:
            type: string
    example:
      kind: folder-moved
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
      aggregate-id: 3e0f7ce312e5
      aggregate-kind: folder
      old-path: web/jabon0007/applications/wi738811/scans
      new-path: web/jabon0007/arrangements/0019212391911/scans
  folder-updated:
    type: object
    description: Folder properties were updated
    allOf:
      - $ref: '#/definitions/event'
      - type: object
        properties:
          path:
            type: string
          changes:
            type: array
            items:
              $ref: '#/definitions/change'
    example:
      kind: folder-updated
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
      aggregate-id: 3e0f7ce312e5
      aggregate-kind: folder
      path: web/jabon0007/applications/wi738811/scans
      updates:
        - name: ou
          old: 2301
          new: 1000
        - name: thumbnail
          old: 'no'
          new: 'yes'
  change:
    type: object
    properties:
      name:
        type: string
      old:
        type: string
      new:
        type: string
  folder-deleted:
    type: object
    description: A folder was deleted
    allOf:
      - $ref: '#/definitions/event'
      - type: object
        properties:
          path:
            type: string
    example:
      kind: folder-deleted
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
      aggregate-id: 3e0f7ce312e5
      aggregate-kind: folder
      path: web/jabon0007/
