swagger: '2.0'
x-asee-visibility: public
host: bankapi.net
basePath: /v1/entitlements
info:
  description: "Entitlements API lets you check and enforce access entitlements with customer mandates, limits and access switches. Mandates are given for account arrangements and can specify allowed services, applicable channels and any limits set for each mandate holder. Mandate model is aligned with ISO 20022. Setting limits for cards access and online access is possible in two modes - *unconstrained* and *constrained*. Unconstrained mode lets you set any limit value within acceptable range while constrained mode makes you pick from a predefined list of limits and limit groups. Access switches enable quick *on/off* control of channels used for card and online access"
  title: Entitlements API
  version: v1
  contact:
    name: Branko Serbula
    url: https://bankapi.net/docs/public/entitlements-getstarted.html
    email: branko.serbula@asseco-see.rs
tags:
- name: Mandates
  description: Working with mandate
- name: Limits
  description: Working with limits  
- name: Card access
  description: Working with card access entitlements 
- name: Online access
  description: Working with online access entitlements   
- name: Classifications
  description: Working with classifications
consumes:
- application/json
produces:
- application/json
schemes:
- https
- http
paths:
  /mandates:
    get:
      summary: Get mandates for customers and arrangements
      description: Response contains list of mandates that match criteria. List of mandate holders for each mandate is not returned by default
      operationId: Mandates_GetList
      parameters:
        - $ref: '#/parameters/arrangements-param'
        - $ref: '#/parameters/customers-param'
        - $ref: '#/parameters/include-param'
        - $ref: '#/parameters/trim-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/mandate-list'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Mandates
      x-asee-tags:
        - Shapeable

  /mandates/{mandate-number}:
    get:
      summary: Get details of specific mandate
      operationId: Mandates_Get
      parameters:
        - $ref: '#/parameters/mandate-number-param'
        - $ref: '#/parameters/include-param'
        - $ref: '#/parameters/trim-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/mandate'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Mandates
      x-asee-tags:
        - Shapeable
  
  /limits/policy:
    get:
      summary: Get limit setting policy
      description: Response contains policy that determines whether limit setting is constrained or unconstrained
      operationId: Limits_GetPolicy
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/limit-setting-policy'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Limits  

  /limits/predefined:
    get:
      summary: Get groups of predefined limits for specific product
      operationId: Limits_GetPredefinedGroups
      description: Response contains list of predefined limit groups for specific product
      parameters:
        - name: product-code
          description: Unique identifier of the product (online service product, card product) for which groups are predefined
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/limit-group-list'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Limits   


  /card-access/{card-number}/limits:
    get:
      summary: Get limits for specific card
      description: "Response contains effective limits and their usage for specific card"
      operationId: CardLimits_GetList
      parameters:
        - $ref: '#/parameters/card-number-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/limit-list'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Card access
    post:
      summary: Set card limit
      description: "Sets new value of card limit"
      operationId: CardLimits_SetLimit
      parameters:
        - $ref: '#/parameters/card-number-param'      
        - name: cmd
          schema:
            $ref: '#/definitions/set-limit-command'
          in: body
          required: true
      responses:
        204:
          description: No content - Limit set
        440:
          description: |
            Your request was well constructed but it could not be processed. Consider the following possible problems and look into response for more details:

            | Problem | Description |
            |-|-|
            | [invalid-service-channel-combination]() | {service} service is not available via {channel} channel |
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Card access

  /card-access/{card-number}/limit-groups:
    get:
      summary: Get groups of card limits for specific card
      description: Response contains list of effective limit groups for specific card
      operationId: CardLimitGroups_Get     
      parameters:
        - $ref: '#/parameters/card-number-param'
        - name: categories
          description: List of limit categories to filter the results 
          in: query
          required: false
          type: array
          minItems: 1
          uniqueItems: true
          collectionFormat: csv
          items:
            type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/limit-group-list'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Card access   
    post:
      summary: Activate group of limits for specific card
      description: "Activate the selected group of cars limits for specific card"
      operationId: CardLimitGroups_Activate
      parameters:
        - $ref: '#/parameters/card-number-param'
        - name: cmd
          schema:
            $ref: '#/definitions/activate-limit-group-command'
          in: body
          required: true
      responses:
        204:
          description: No content - Limit group activated
        440:
          description: |
            Your request was well constructed but it could not be processed. Consider the following possible problems and look into response for more details:

            | Problem | Description |
            |-|-|
            | [group-not-applicable]() | Group {group} is not applicable to {product} product |
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Card access        

  /card-access/{card-number}/switches:
    get:
      summary: Get state of card access switches for specific card
      description: "Response contains state of card access switches (eg. use-atm, use-pos, use-vpos) for specific card"
      operationId: CardSwitches_Get     
      parameters:
        - $ref: '#/parameters/card-number-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/switch-list'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Limits    
    post:
      summary: Set the state of specific card access switch
      description: "Sets the state of card access switch for specific card"
      operationId: CardSwitches_Set
      parameters:
        - $ref: '#/parameters/card-number-param'
        - name: cmd
          schema:
            $ref: '#/definitions/set-access-switch-command'
          in: body
          required: true
      responses:
        204:
          description: No content - Card access switch set
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Card access    

  /online-access/{customer-number}/limits:
    get:
      summary: Get online limits for specific customer
      description: "Response contains effective limits and their usage for online channels"
      operationId: OnlineLimits_GetList
      parameters:
        - $ref: '#/parameters/customer-number-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/limit-list'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Online access
    post:
      summary: Set online limit
      description: "Sets new value of online limit"
      operationId: OnlineLimits_Set
      parameters:
        - $ref: '#/parameters/customer-number-param'
        - name: cmd
          schema:
            $ref: '#/definitions/set-limit-command'
          in: body
          required: true
      responses:
        204:
          description: No content - Online limit set
        440:
          description: |
            Your request was well constructed but it could not be processed. Consider the following possible problems and look into response for more details:

            | Problem | Description |
            |-|-|
            | [invalid-service-channel-combination]() | {service} service is not available via {channel} channel |
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Online access

  /online-access/{customer-number}/limit-groups:
    get:
      summary: Get groups of online limits for specific customer
      description: "Response contains effective groups of online limits for specific customer"
      operationId: OnlineLimitGroups_GetList
      parameters:
        - $ref: '#/parameters/customer-number-param'      
        - name: categories
          description: List of limit categories to filter the results 
          in: query
          required: false
          type: array
          minItems: 1
          uniqueItems: true
          collectionFormat: csv
          items:
            type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/limit-group-list'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Online access   
    post:
      summary: Activate predefined group of online limits for specific customer
      description: "Activates the selected group of online limits for specific customer"
      operationId: OnlineLimitGroups_Activate
      parameters:
        - $ref: '#/parameters/customer-number-param'
        - name: cmd
          schema:
            $ref: '#/definitions/activate-limit-group-command'
          in: body
          required: true
      responses:
        204:
          description: No content - Online limit group activated
        440:
          description: |
            Your request was well constructed but it could not be processed. Consider the following possible problems and look into response for more details:

            | Problem | Description |
            |-|-|
            | [group-not-applicable]() | Group {group} is not applicable to {product} product |
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Online access
     

# ****************************************************#
# ENDPOINTS COMMON WITH OTHER APIs                    #
# ****************************************************#

  /classifications:
    get:
      summary: List all classification schemas used by the API
      description: Some fields and parameters have been restricted to a list of allowed lookup values maintained by the bank. This method lists all schemas used in this API.
      operationId: "Classifications_GetList"
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/classification-list'
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Classifications

  /classifications/{schema-id}:
    get:
      summary: List values allowed by given classification schema.
      description: Returns all classification values for chosen classification.
      operationId: Classifications_Get
      parameters:
        - $ref: '#/parameters/schema-id-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/classification'
        default:
          $ref: '#/responses/default-error-response'

      tags:
        - Classifications

parameters:
# ****************************************************#
# PARAMETERS COMMON WITH OTHER APIs                   #
# ****************************************************#
  schema-id-param:
    name: schema-id
    description: Identifier of classification schema
    in: path
    required: true
    type: string
  include-param:
    description: List of fields to include in response. For more information see general guidance on [response shaping](common-getstarted.html#shaping)
    in: query
    name: include
    type: array
    items:
      type: string
    collectionFormat: csv
    x-asee-common: true
  trim-param:
    description: List of fields to trim from response. For more information see general guidance on [response shaping](common-getstarted.html#shaping)
    in: query
    name: trim
    type: array
    items:
      type: string
    collectionFormat: csv
    x-asee-common: true
# ****************************************************#
# PARAMETERS SPECIFIC TO THIS API                     #
# ****************************************************#
  arrangements-param:
    description: List of identifiers of the arrangements for which mandates are inquired. Mandatory if `customers` param is not present.
    in: query
    name: arrangements
    required: false
    type: array
    minItems: 1
    uniqueItems: true
    collectionFormat: csv
    items:
      type: string

  customers-param:
    description: List of identifiers of mandate holders for which mandates are inquired. Mandatory if `arrangements` param is not present.
    in: query
    name: customers
    required: false
    type: array
    minItems: 1
    uniqueItems: true
    collectionFormat: csv
    items:
      type: string
      
  customer-number-param:
    description: Unique identifier of the customer
    in: path
    name: customer-number
    required: true
    type: string

  card-number-param:
    description: Unique and unambiguous identification of the card. Could be PAN or some form of tokenized identifer.
    in: path
    name: card-number
    required: true
    type: string   
     
  mandate-number-param:
    description: Unique and unambiguous identification of the mandate
    in: path
    name: mandate-number
    required: true
    type: string

definitions:
  classification-value:
    type: object
    description: Classification value
    properties:
      literal:
        description: Literal that uniquely identifies classification value
        type: string
      code:
        description: Optional numerical code of classification value
        type: string
      description:
        description: Description of classification value
        type: string
      parent-literal:
        description: Optional literal of parent classification value if schema is hierarchical
        type: string
    example:
      literal: billing
      code: "2"
      description: Contact may be used to provide party with details of their liabilities to the bank

  classification-list:
    description: List of classification schemas
    type: object
    properties:
      items:
        description: List of classification schemas
        items:
          $ref: "#/definitions/classification-info"
        type: array
    example:
      -
        schema-id: filing-purpose
        name: Filing Purpose
        description: List of possible uses of document in business context. Commonly used filing purposes are document, customer-picture
      -
        schema-id: folder-purpose
        name: Folder Purpose
        description: List of possible uses of a folder in business context.

  classification-info:
    description: Basic information on classification schema
    properties:
      schema-id:
        type: string
        description: Unique literal that identifies the classification schema. Always in `lowercase-dash` convention.
      name:
        type: string
        description: User friendly name of classification
      description:
        type: string
        description: Description of a classification
    example:
      schema-id: filing-purpose
      name: Filing Purpose
      description: List of possible uses of document in business context. Commonly used filing purposes are document, customer-picture

  classification:
    type: object
    description: Classification schema details
    properties:
      schema-id:
        type: string
        description: Unique literal that identifies the classification schema. Always in `lowercase-dash` convention.
      name:
        type: string
        description: User friendly name of classification
      description:
        type: string
        description: Description of a classification
      values:
        description: List of allowed classification values
        type: array
        items:
          $ref: "#/definitions/classification-value"
    example:
      schema-id: contact-purpose
      name: Contact Purpose
      description: List of possible uses of contact in business context. Commonly used filing purposes are billing, marketing
      values:
        - literal: billing
          code: "1"
          description: Contact may be used to provide party with details of their liabilities to the bank
        - literal: marketing
          code: "2"
          description: Contact may be used to provide party with details of offers
        - literal: reporting
          code: "3"
          description: Contact may be used to provide party with reports on their account


  mandate-list:
    type: array
    items:
      $ref: '#/definitions/mandate'
    example:

  mandate:
    description: Entitlement of mandate holder to access services for an arrangement
    required:
      - mandate-id
      - arrangement-number
      - applicable-channels
      - allowed-services
      - mandate-holders
      - effective-date
    properties:
      mandate-id:
        type: string
        description: Unique and unambiguous identification of the mandate
      arrangement-number:
        type: string
        description: Unique identifier of the account arrangement that is the object of the mandate
      arrangement-kind:
        description: |
          Primary enumeration of arrangements according to product type
          For a list of possible values see [arrangement-kind-param](arrangement-classifications.html#arrangement-kinds) enumeration.
        type: string
        enum:
          - current-account
          - demand-deposit
          - term-deposit
          - term-loan
          - overdraft-facility
          - credit-facility
          - credit-card-facility
          - card-access-arrangement
          - electronic-acess-arrangement
          - other-product-arrangement
      customer-number:
        description: "Identification of the mandate holder in bank's records"
        type: string
      applicable-channels:
        type: array
        description: |
          "Channel for which the operation mandate is valid. If applicable-channels equals `fax`, this means that a bank operation instruction sent by fax will be processed according to the mandate"
          For a list of possible values see [channels](entitlements-classifications.html#channels) enumeration.
        minItems: 1
        uniqueItems: true
        items:
          type: string
          enum:  [online, branch, call-center, atm, pos, vpos, any]
      allowed-services:
        type: array
        description: |
          "List of bank services allowed by the mandate. These are groupings of more granular operations"
          For a list of possible values see [bank-services](entitlements-classifications.html#bank-services) classification.
        minItems: 1
        uniqueItems: true
        items:
          type: string
          x-asee-classification: bank-services
      effective-date:
        type: string
        format: date
        description: Date when the mandate becomes valid
      end-date:
        type: string
        format: date
        description: Date when the mandate stops to be valid
      required-signatures-number:
        type: integer
        format: int32
        description: "Number of required and necessary signatures by the mandate"
      signature-order:
        type: boolean
        description: "Indicator whether a certain order of signatures has to be respected or not"
      mandate-holders:
        type: array
        items:
          $ref: '#/definitions/mandate-holder'

    example:
      mandate-number: 171-2015
      arrangement-number: "00301000121312"
      arrangement-kind: current-account
      applicable-channels: [any]
      allowed-services: [any]
      effective-date: 2015-11-12
      mandate-holders:
        -
          customer-number: pepe037
          customer-name: Petar Petrovic
        -
          customer-number: mipe022
          customer-name: Milena Petrovic
          limits:
            - # weekly withdrawal limit for Milena Petrovic
              kind: period-limit  
              period: P7D
              amount: 100000
              count: 10  
              currency: RSD                     
              service: withdrawal
              channel: any
            - # maximum amount of single withdrawal for Milena Petrovic 
              kind: transaction-limit  
              amount: 20000
              currency: RSD                     
              service: withdrawal
              channel: any

  mandate-holder:
    description: Holder of the mandate
    required:
      - customer-number
      - customer-name
    properties:
      customer-number:
        description: Identification of the mandate holder in bank's records
        type: string
      customer-name:
        description: Name of the mandate holder in bank's records
        type: string
      is-owner:
        type: boolean
        description: Whether a mandate holder is owner of account
      signature-order:
        description: Order in which the mandate holder has to sign
        type: integer
        format: int32
      limits:
        description: Limits of authorization granted to a mandate holder
        type: array
        items: 
          $ref: '#/definitions/limit-condition'

  limit-condition:
    description: Specification od the limit details
    properties:
      kind:
        description: |
          For a list of possible values see [limit-kinds](entitlements-classifications.html#limit-kinds) enumeration.
        type: string
        enum: [transaction-limit, period-limit]
        x-asee-enumeration: limit-kinds
      period:
        description: Period for which limit applies. Specified as a ISO 8601 duration. Usualy dayly or monthly, but could be more specific.
        type: string
        format: ISO 8601 duration
      amount:
        description: Monetary amount allowed in period or per transaction
        format: double
        type: number
        minimum: 0
      count:
        description: Number of transactions allowed in the period
        type: integer
        format: int32
        minimum: 0  
      currency:
        description: ISO 4217 3 letter currency code
        type: string
        minLength: 3
        maxLength: 3                     
      service:
        description: |
          Bank's service tracked by the limit.
          For a list of possible values see [bank-services](entitlements-classifications.html#bank-services) classification.
        type: string
        x-asee-classification: bank-services
        default: any
      channel:
        type: string
        description: |
          Channel tracked by the limit. If channel is not relevant expected value is `any`.
          For a list of possible values see [channels](entitlements-classifications.html#channels) enumeration.
        enum: [online, branch, call-center, atm, pos, vpos, any]
        x-asee-enumeration: channels
    example:
      kind: period-limit  
      period: P7D
      amount: 100000
      count: 10  
      currency: RSD                     
      service: withdrawal
      channel: atm
 

  limit-usage:
    description: Used balance of the limit
    properties:
      used-amount:
        description: Amount of limit that has been already used
        type: number
        format: double
      remaining-amount:
        description: Amount of limit that is still remaining
        type: number
        format: double
      used-count:
        description: Number of transactions already used
        type: integer
        format: int32
        minimum: 0  
      remaining-count:
        description: Number of transactions still remaining
        type: integer
        format: int32
        minimum: 0        
    example:
      used-amount: 100.00
      remaining-amount: 1234.00
      used-count: 1
      remaining-count: 9

  limit:
    description: Actual limit  
    properties:
      limit-id:
        type: string
        description: Unique identifier of the limit
      limit-group:
        type: string
        description: Unique identifier of limit group if limit was set as a part of a group.
      period-reset:
        description: Date and time when limit usage will be reset
        type: string
        format: date-time        
      condition:
        $ref: '#/definitions/limit-condition'
      usage:
        $ref: '#/definitions/limit-usage'     

  limit-group:
    description: Predefined group of related limits that customer can pick. Customer chooses one of the predefined limit groups from the same category.
    properties:
      name:
        type: string
        description: Name of the limit group
      description:
        type: string
        description: Description of the limit group    
      category:
        type: string
        description: |
          Catogories of limits such as `domestic-card-use`, `cross-border-card-use`. Only one limit group can be effective within same category.
          For a list of possible values see [limit-categories](entitlements-classifications.html#limit-categories) classification.
        x-asee-classification: limit-categories       
      limits:
        type: array
        description: List of limits within a group
        items:
          $ref: '#/definitions/limit-condition'

  
  limit-setting-policy:
    type: object
    description: Policy for limit setting
    properties:
      online-limit-setting:
        type: string
        description: Mode of limit setting allowed by online limit system. Constrained mode requires selection of predefined limit groups.
        enum: [constrained, unconstrained]
      card-limit-setting:
        type: string
        description: Mode of limit setting allowed by card limit system. Constrained mode requires selection of predefined limit groups.
        enum: [constrained, unconstrained]       
    example:
      online-limit-setting: unconstrained
      card-limit-setting: constrained
        
  limit-list:
    type: array
    description: List of limits
    items:
      $ref: '#/definitions/limit'
    example:
      - 
        limit-id: CL-123
        period-reset: 2016-07-14T00:00:00
        limit-group: domestic-2
        conditon:
          kind: period-limit  
          period: P7D
          amount: 500000
          count: 50  
          currency: RSD                     
          service: withdrawal
          channel: any
        usage:
          used-amount: 100000.00
          remaining-amount: 400000.00
          used-count: 11
          remaining-count: 39
      - 
        limit-id: CL-124
        period-reset: 2016-07-14T00:00:00
        limit-group: domestic-2
        conditon:
          kind: period-limit  
          period: P7D
          amount: 1000
          count: 10  
          currency: EUR                     
          service: payment
          channel: any
        usage:
          used-amount: 179.50
          remaining-amount: 820.50
          used-count: 1
          remaining-count: 9  

  limit-group-list:
    type: array
    description: List of limit groups
    items:
      $ref: '#/definitions/limit-group'
    example:
      - 
        name: domestic-2
        description: Domestic limit group 2   
        category: domestic-card-use   
        limits:
          - 
            kind: period-limit  
            period: P7D
            amount: 500000
            count: 50  
            currency: RSD                     
            service: withdrawal
            channel: any
          - 
            kind: period-limit  
            period: P7D
            amount: 500000
            count: 50  
            currency: RSD                     
            service: payment
            channel: any
      - 
        name: cross-border-2
        description: Cross border limit group 2   
        category: cross-border-card-use   
        limits:
          - 
            kind: period-limit  
            period: P7D
            amount: 5000
            count: 40  
            currency: EUR                     
            service: withdrawal
            channel: any
          - 
            kind: period-limit  
            period: P7D
            amount: 5000
            count: 40  
            currency: EUR                     
            service: payment
            channel: any            
  
  activate-limit-group-command:
    type: object
    description: Command with parameters to activate limit group
    properties:
      group-id: 
        type: string
        description: Unique identifier of selected limit group
        
  set-limit-command:
    type: object
    description: Command with parameters to set new limit value
    properties:
      limit-id:
        type: string
        description: Unique identifier of the limit     
      limit-value: 
        $ref: '#/definitions/limit-condition'
  
  set-access-switch-command:
    type: object
    description: Command with parameters to set access switch
    properties:
      switch-kind:
        type: string
        description: Kind of access switch
        enum: [enable-atm, enable-pos, enable-vpos]
      switch-state:
        type: string
        description: State of access switch
        enum: [on, off]      
  
  access-switch:
    type: object
    description: Access switch
    properties:
      switch-kind:
        type: string
        description: |
          Kind of access switch.
          For description of allowed values see [channels](entitlements-classifications.html#switch-kinds) enumeration.
        enum: [enable-atm, enable-pos, enable-vpos]
        x-asee-enumeration: switch-kinds
      switch-state:
        type: string
        description: State of access switch
        enum: [on, off]
        x-asee-enumeration: channels        
  
  switch-list:
    type: array
    items:
      $ref: '#/definitions/access-switch'
    

responses:
  default-error-response:
    description: 'Besides specific status codes above, other standard http [status codes](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) can be returned for each request. To learn more see general guidance on [error handling](common-getstarted.html#error-handling)'